### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by RozeFound** [tyra314/modweaver#1]
When trying to do something it always ends with about hundred repeated message "Event loop is closed"

**Comment by tyra314** [comment]
Hey, thanks for trying. Which Python version are you using? 

Can you run the command again but with the `--debug` argument and post the log here?

**Comment by RozeFound** [comment]
Oh sorry, I forgot about details.

OS: Winodws 11
Python: 3.9.5

Log: https://pastebin.com/QFb52YBU

**Comment by tyra314** [comment]
Well, something is different on Windows. Should be fine now.

**Comment by RozeFound** [comment]
Yep, now all perfectly working
