### ISSUE TITLE
Modrinth statement in README is untrue

### ISSUE THREAD

**Issue by triphora** [tyra314/modweaver#3]
Hi,
The section [here](https://github.com/tyra314/modweaver#modrinth-authentification) is entirely untrue. You do not need a token to access public mods on Modrinth's API. You only need one to send `POST`, `PATCH`, or `DELETE` requests, or `GET` requests on private resources such as rejected/draft/pending mods (that mod's team, Moderators, and Admins only) or dashboard stuff.
Since ModWeaver should only be accessing public, approved mods, a token isn't needed unless users want to add their own rejected/draft/pending mods.

**Comment by tyra314** [comment]
Oh, good to know, thanks. So I can remove the token code completely.
